const mongoose = require("mongoose");
const db = require("../models");
const axios = require("axios");

mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost/spellBooks", {
  useNewUrlParser: true,
  useUnifiedTopology: true
});


var srdList = [
"Acid Splash",
"Chill Touch",
"Dancing Lights",
"Druidcraft",
"Eldritch Blast",
"Fire Bolt",
"Guidance",
"Light",
"Mage Hand",
"Mending",
"Message",
"Minor Illusion",
"Poison Spray",
"Prestidigitation",
"Produce Flame",
"Ray of Frost",
"Resistance",
"Sacred Flame",
"Shillelagh",
"Shocking Grasp",
"Spare the Dying",
"Thaumaturgy",
"True Strike",
"Vicious Mockery",
"Alarm",
"Animal Friendship",
"Bane",
"Bless",
"Burning Hands",
"Charm Person",
"Chromatic Orb",
"Color Spray",
"Command",
"Comprehend Languages",
"Create or Destroy Water",
"Cure Wounds",
"Detect Evil and Good",
"Detect Magic",
"Detect Poison and Disease",
"Disguise Self",
"Dissonant Whispers",
"Divine Favor",
"Entangle",
"Expeditious Retreat",
"Faerie Fire",
"False Life",
"Feather Fall",
"Find Familiar",
"Floating Disk",
"Fog Cloud",
"Goodberry",
"Grease",
"Guiding Bolt",
"Healing Word",
"Hellish Rebuke",
"Heroism",
"Hideous Laughter",
"Hunter's Mark",
"Identify",
"Illusory Script",
"Inflict Wounds",
"Jump",
"Longstrider",
"Mage Armor",
"Magic Missile",
"Protection from Evil and Good",
"Purify Food and Drink",
"Sanctuary",
"Shield",
"Shield of Faith",
"Silent Image",
"Sleep",
"Speak with Animals",
"Thunderwave",
"Unseen Servant",
"Wrathful Smite",
"Acid Arrow",
"Aid",
"Alter Self",
"Animal Messenger",
"Arcane Lock",
"Arcanist's Magic Aura",
"Augury",
"Barkskin",
"Blindness/Deafness",
"Blur",
"Branding Smite",
"Calm Emotions",
"Continual Flame",
"Darkness",
"Darkvision (Spell)",
"Detect Thoughts",
"Enhance Ability",
"Enlarge/Reduce",
"Enthrall",
"Find Steed",
"Find Traps",
"Flame Blade",
"Flaming Sphere",
"Gentle Repose",
"Gust of Wind",
"Heat Metal",
"Hold Person",
"Invisibility",
"Knock",
"Lesser Restoration",
"Levitate",
"Locate Animals or Plants",
"Locate Object",
"Magic Mouth",
"Magic Weapon",
"Mirror Image",
"Misty Step",
"Moonbeam",
"Pass without Trace",
"Prayer of Healing",
"Protection from Poison",
"Ray of Enfeeblement",
"Rope Trick",
"Scorching Ray",
"See Invisibility",
"Shatter",
"Silence",
"Spider Climb",
"Spike Growth",
"Spiritual Weapon",
"Suggestion",
"Warding Bond",
"Web",
"Zone of Truth",
"Animate Dead",
"Beacon of Hope",
"Bestow Curse",
"Blink",
"Call Lightning",
"Clairvoyance",
"Conjure Animals",
"Counterspell",
"Create Food and Water",
"Daylight",
"Dispel Magic",
"Fear",
"Feign Death",
"Fireball",
"Fly",
"Gaseous Form",
"Glyph of Warding",
"Haste",
"Hypnotic Pattern",
"Lightning Bolt",
"Magic Circle",
"Major Image",
"Mass Healing Word",
"Meld into Stone",
"Nondetection",
"Phantom Steed",
"Plant Growth",
"Protection from Energy",
"Remove Curse",
"Revivify",
"Sending",
"Sleet Storm",
"Slow",
"Speak with Dead",
"Speak with Plants",
"Spirit Guardians",
"Stinking Cloud",
"Tiny Hut",
"Tongues",
"Vampiric Touch",
"Water Breathing",
"Water Walk",
"Wind Wall",
"Arcane Eye",
"Banishment",
"Black Tentacles",
"Blight",
"Compulsion",
"Confusion",
"Conjure Minor Elementals",
"Conjure Woodland Beings",
"Control Water",
"Death Ward",
"Dimension Door",
"Divination",
"Dominate Beast",
"Fabricate",
"Faithful Hound",
"Fire Shield",
"Freedom of Movement",
"Giant Insect",
"Greater Invisibility",
"Guardian of Faith",
"Hallucinatory Terrain",
"Ice Storm",
"Locate Creature",
"Phantasmal Killer",
"Polymorph",
"Private Sanctum",
"Resilient Sphere",
"Secret Chest",
"Stone Shape",
"Stoneskin",
"Wall of Fire",
"Animate Objects",
"Antilife Shell",
"Arcane Hand",
"Awaken",
"Cloudkill",
"Commune",
"Commune with Nature",
"Cone of Cold",
"Conjure Elemental",
"Contact Other Plane",
"Contagion",
"Creation",
"Dispel Evil and Good",
"Dominate Person",
"Dream",
"Flame Strike",
"Geas",
"Greater Restoration",
"Hallow",
"Hold Monster",
"Insect Plague",
"Legend Lore",
"Mass Cure Wounds",
"Mislead",
"Modify Memory",
"Passwall",
"Planar Binding",
"Raise Dead",
"Reincarnate",
"Scrying",
"Seeming",
"Telekinesis",
"Telepathic Bond",
"Teleportation Circle",
"Tree Stride",
"Wall of Force",
"Wall of Stone",
"Blade Barrier",
"Chain Lightning",
"Circle of Death",
"Conjure Fey",
"Contingency",
"Create Undead",
"Disintegrate",
"Eyebite",
"Find the Path",
"Flesh to Stone",
"Forbiddance",
"Freezing Sphere",
"Globe of Invulnerability",
"Guards and Wards",
"Harm",
"Heal",
"Heroes' Feast",
"Instant Summons",
"Irresistible Dance",
"Magic Jar",
"Mass Suggestion",
"Move Earth",
"Planar Ally",
"Programmed Illusion",
"Sunbeam",
"Transport via Plants",
"True Seeing",
"Wall of Ice",
"Wall of Thorns",
"Wind Walk",
"Word of Recall",
"Arcane Sword",
"Conjure Celestial",
"Delayed Blast Fireball",
"Divine Word",
"Etherealness",
"Finger of Death",
"Fire Storm",
"Forcecage",
"Magnificent Mansion",
"Mirage Arcane",
"Plane Shift",
"Prismatic Spray",
"Project Image",
"Regenerate",
"Resurrection",
"Reverse Gravity",
"Sequester",
"Simulacrum",
"Symbol",
"Teleport",
"Animal Shapes",
"Antimagic Field",
"Antipathy/Sympathy",
"Clone",
"Control Weather",
"Demiplane",
"Dominate Monster",
"Earthquake",
"Feeblemind",
"Glibness",
"Holy Aura",
"Incendiary Cloud",
"Maze",
"Mind Blank",
"Power Word Stun",
"Sunburst",
"Telepathy",
"Astral Projection",
"Foresight",
"Gate",
"Imprisonment",
"Mass Heal",
"Meteor Swarm",
"Power Word Kill",
"Prismatic Wall",
"Shapechange",
"Storm of Vengeance",
"Time Stop",
"True Polymorph",
"True Resurrection",
"Weird",
"Wish",
]

var beegSpellList = [
  "Acid Splash",
  "Blade Ward",
  "Chill Touch",
  "Dancing Lights",
  "Druidcraft",
  "Eldritch Blast",
  "Fire Bolt",
  "Friends",
  "Guidance",
  "Light",
  "Mage Hand",
  "Mending",
  "Message",
  "Minor Illusion",
  "Poison Spray",
  "Prestidigitation",
  "Produce Flame",
  "Ray of Frost",
  "Resistance",
  "Sacred Flame",
  "Shillelagh",
  "Shocking Grasp",
  "Spare The Dying",
  "Thaumaturgy",
  "Thorn Whip",
  "True Strike",
  "Vicious Mockery",
  "Alarm",
  "Animal Friendship",
  "Armor of Agathys",
  "Arms of Hadar",
  "Bane",
  "Bless",
  "Burning Hands",
  "Charm Person",
  "Chromatic Orb",
  "Color Spray",
  "Command",
  "Compelled Duel",
  "Comprehend Languages",
  "Create or Destroy Water",
  "Cure Wounds",
  "Detect Evil and Good",
  "Detect Magic",
  "Detect Poison and Disease",
  "Disguise Self",
  "Dissonant Whispers",
  "Divine Favor",
  "Ensnaring Strike",
  "Entangle",
  "Expeditious Retreat",
  "Faerie Fire",
  "False Life",
  "Feather Fall",
  "Find Familiar",
  "Fog Cloud",
  "Goodberry",
  "Grease",
  "Guiding Bolt",
  "Hail of Thorns",
  "Healing Word",
  "Hellish Rebuke",
  "Heroism",
  "Hex",
  "Hunters Mark",
  "Identify",
  "Illusory Script",
  "Inflict Wounds",
  "Jump",
  "Longstrider",
  "Mage Armor",
  "Magic Missile",
  "Protection from Evil and Good",
  "Purify Food and Drink",
  "Ray of Sickness",
  "Sanctuary",
  "Searing Smite",
  "Shield",
  "Shield of Faith",
  "Silent Image",
  "Sleep",
  "Speak with Animals",
  "Hideous Laughter",
  "Floating Disk",
  "Thunderous Smite",
  "Thunderwave",
  "Unseen Servant",
  "Witch Bolt",
  "Wrathful Smite",
  "Aid",
  "Alter Self",
  "Animal Messenger",
  "Arcane Lock",
  "Augury",
  "Barkskin",
  "Beast Sense",
  "Blindness/Deafness",
  "Blur",
  "Branding Smite",
  "Calm Emotions",
  "Cloud of Daggers",
  "Continual Flame",
  "Cordon of Arrows",
  "Crown of Madness",
  "Darkness",
  "Darkvision",
  "Detect Thoughts",
  "Enhance Ability",
  "Enlarge/Reduce",
  "Enthrall",
  "Find Steed",
  "Find Traps",
  "Flame Blade",
  "Flaming Sphere",
  "Gentle Repose",
  "Gust of Wind",
  "Heat Metal",
  "Hold Person",
  "Invisibility",
  "Knock",
  "Lesser Restoration",
  "Levitate",
  "Locate Animals or Plants",
  "Locate Object",
  "Magic Mouth",
  "Magic Weapon",
  "Acid Arrow",
  "Mirror Image",
  "Misty Step",
  "Moonbeam",
  "Magic Aura",
  "Pass without Trace",
  "Phantasmal Force",
  "Prayer of Healing",
  "Protection from Poison",
  "Ray of Enfeeblement",
  "Rope Trick",
  "Scorching Ray",
  "See Invisibility",
  "Shatter",
  "Silence",
  "Spider Climb",
  "Spike Growth",
  "Spiritual Weapon",
  "Suggestion",
  "Warding Bond",
  "Web",
  "Zone of Truth",
  "Animate Dead",
  "Aura of Vitality",
  "Beacon of Hope",
  "Bestow Curse",
  "Blinding Smite",
  "Blink",
  "Call Lightning",
  "Clairvoyance",
  "Conjure Animals",
  "Conjure Barrage",
  "Counterspell",
  "Create Food and Water",
  "Crusader’s Mantle",
  "Daylight",
  "Dispel Magic",
  "Elemental Weapon",
  "Fear",
  "Feign Death",
  "Fireball",
  "Fly",
  "Gaseous Form",
  "Glyph of Warding",
  "Haste",
  "Hunger of Hadar",
  "Hypnotic Pattern",
  "Tiny Hut",
  "Lightning Arrow",
  "Lightning Bolt",
  "Magic Circle",
  "Major Image",
  "Mass Healing Word",
  "Meld into Stone",
  "Nondetection",
  "Phantom Steed",
  "Plant Growth",
  "Protection from Energy",
  "Remove Curse",
  "Revivify",
  "Sending",
  "Sleet Storm",
  "Slow",
  "Speak with Dead",
  "Speak with Plants",
  "Spirit Guardians",
  "Stinking Cloud",
  "Tongues",
  "Vampiric Touch",
  "Water Breathing",
  "Water Walk",
  "Wind Wall",
  "Arcane Eye",
  "Aura of Life",
  "Aura of Purity",
  "Banishment",
  "Blight",
  "Compulsion",
  "Confusion",
  "Conjure Minor Elementals",
  "Conjure Woodland Beings",
  "Control Water",
  "Death Ward",
  "Dimension Door",
  "Divination",
  "Dominate Beast",
  "Black Tentacles",
  "Fabricate",
  "Fire Shield",
  "Freedom of Movement",
  "Giant Insect",
  "Grasping Vine",
  "Greater Invisibility",
  "Guardian of Faith",
  "Hallucinatory Terrain",
  "Ice Storm",
  "Secret Chest",
  "Locate Creature",
  "Faithful Hound",
  "Private Sanctum",
  "Resilient Sphere",
  "Phantasmal Killer",
  "Polymorph",
  "Staggering Smite",
  "Stone Shape",
  "Stoneskin",
  "Wall of Fire",
  "Animate Objects",
  "Antilife Shell",
  "Awaken",
  "Banishing Smite",
  "Circle of Power",
  "Cloudkill",
  "Commune",
  "Commune with Nature",
  "Cone of Cold",
  "Conjure Elemental",
  "Conjure Volley",
  "Contact Other Plane",
  "Contagion",
  "Creation",
  "Destructive Wave",
  "Dispel Evil and Good",
  "Dominate Person",
  "Dream",
  "Flame Strike",
  "Geas",
  "Greater Restoration",
  "Hallow",
  "Hold Monster",
  "Insect Plague",
  "Legend Lore",
  "Mass Cure Wounds",
  "Mislead",
  "Modify Memory",
  "Passwall",
  "Planar Binding",
  "Raise Dead",
  "Telepathic Bond",
  "Reincarnate",
  "Scrying",
  "Seeming",
  "Swift Quiver",
  "Telekinesis",
  "Teleportation Circle",
  "Tree Stride",
  "Wall of Force",
  "Wall of Stone",
  "Arcane Gate",
  "Blade Barrier",
  "Chain Lightning",
  "Circle of Death",
  "Conjure Fey",
  "Contingency",
  "Create Undead",
  "Disintegrate",
  "Instant Summons",
  "Eyebite",
  "Find the Path",
  "Flesh to Stone",
  "Forbiddance",
  "Globe of Invulnerability",
  "Guards and Wards",
  "Harm",
  "Heal",
  "Heroes’ Feast",
  "Magic Jar",
  "Mass Suggestion",
  "Move Earth",
  "Freezing Sphere",
  "Irresistible Dance",
  "Planar Ally",
  "Programmed Illusion",
  "Sunbeam",
  "Transport via Plants",
  "True Seeing",
  "Wall of Ice",
  "Wall of Thorns",
  "Wind Walk",
  "Word of Recall",
  "Conjure Celestial",
  "Delayed Blast Fireball",
  "Divine Word",
  "Etherealness",
  "Finger of Death",
  "Fire Storm",
  "Forcecage",
  "Mirage Arcane",
  "Magnificent Mansion",
  "Plane Shift",
  "Prismatic Spray",
  "Project Image",
  "Regenerate",
  "Resurrection",
  "Reverse Gravity",
  "Sequester",
  "Simulacrum",
  "Symbol",
  "Teleport",
  "Animal Shapes",
  "Antimagic Field",
  "Antipathy/Sympathy",
  "Clone",
  "Control Weather",
  "Demiplane",
  "Dominate Monster",
  "Earthquake",
  "Feeblemind",
  "Glibness",
  "Holy Aura",
  "Incendiary Cloud",
  "Maze",
  "Mind Blank",
  "Power Word Stun",
  "Sunburst",
  "Telepathy",
  "Tsunami",
  "Astral Projection",
  "Foresight",
  "Gate",
  "Imprisonment",
  "Mass Heal",
  "Meteor Swarm",
  "Power Word Heal",
  "Power Word Kill",
  "Prismatic Wall",
  "Shapechange",
  "Storm of Vengeance",
  "Time Stop",
  "True Polymorph",
  "True Resurrection",
  "Weird",
  "Wish",
];

function testConvert() {
  var spellList = ["Armor of Agythes"];

  spellList.forEach((el) => {
    var spellName = el.toLowerCase().replace(/ /g, "-");
    console.log(spellName);
  });
}

function convertShit() {
  var smolSpellList = [];
  srdList.forEach((element) => {
    var spellName = element.toLowerCase().replace(/ /g, "-");

    smolSpellList.push(spellName);
  });
  lookUpShit(smolSpellList);
}

function lookUpShit(list) {
  list.forEach((el) => {

    var URI = `https://www.dnd5eapi.co/api/spells/${el}/`
    var encodedURI = encodeURI(URI)

    axios
      .get(encodedURI)
      .then(function (res) {
        var newEntry = {
          spell_name: res.data.name,
          name: res.data.index,
          desc: res.data.desc,
          higher_level: res.data.higher_level,
          range: res.data.range,
          components: res.data.components,
          ritual: res.data.ritual,
          duration: res.data.duration,
          concentration: res.data.concentration,
          casting_time: res.data.casting_time,
          level: res.data.level,
          damage: res.data.damage,
          heal_at_slot_level: res.data.heal_at_slot_level,
          dc: res.data.dc,
          area_of_effect: res.data.area_of_effect,
          classes: res.data.classes,
        };
        enterThatShit(newEntry);
      })
      .catch((err) => {
        console.log(err);
      });
  });
}

function enterThatShit(entry) {
  // console.log(entry);
  db.Spells.create(entry)
    .then((data) => {
      console.log(data.name)
      // console.log(data);
      process.exit(0);
    })
    .catch((err) => {
      // console.error(err);
      process.exit(1);
    });
}

db.Spells.deleteMany({});
convertShit();

// testConvert()